### ISSUE TITLE
Script fails when file is not there

### ISSUE THREAD

**Issue by ktk** [zazuko/lod.lobbywatch.ch#1]
https://github.com/zazuko/lod.lobbywatch.ch/blob/5264855a73d44274b8e34e9233b8af0a4caf8f37/stardog-scripts/load.sh#L10

This does not work on my system when the file is not there on the first run. It fails and ends the script.

**Comment by vhf** [comment]
Thanks, fixed: https://github.com/zazuko/lod.lobbywatch.ch/blob/7aed8030b83e6a6adec360623025c4a658aae2bb/ontop-scripts/1-convert.sh#L19
